python

diff --git a/.github/workflows/azure-functions-app-java.yml b/.github/workflows/azure-functions-app-java.yml
--- a/.github/workflows/azure-functions-app-java.yml
+++ b/.github/workflows/azure-functions-app-java.yml
@@ -43,6 +43,7 @@ jobs:
             inherit
 
     get-secret:
+        needs: generate-secrets
         uses: ./.github/workflows/dynamic-secrets-access.yml
         with:
             SECRETS_LIST: 'SECRET, SECRET_2'
@@ -77,7 +78,7 @@ jobs:
 
     build-and-deploy:
         runs-on: ubuntu-latest # For Linux, use ubuntu-latest
-        needs: [ generate-secrets ]
+        needs: [ generate-secrets, get-secret, restore-secrets ]
         environment: dev
         steps:
             -   run: |
@@ -145,7 +146,11 @@ jobs:
                 uses: azure/CLI@v1
                 with:
                     inlineScript: |
-                        echo secret=$(az keyvault secret show --vault-name MyVaultName --name MySecret --query value --out tsv) >> $GITHUB_ENV
+                        if ! secret=$(az keyvault secret show --vault-name "${{ secrets.CI_KEY_VAULT_NAME }}" --name MySecret --query value --out tsv 2>/dev/null); then
+                            echo "Failed to fetch secret from Key Vault"
+                            exit 1
+                        fi
+                        echo "secret=$secret" >> $GITHUB_ENV
             #            -   name: Use the value
             #                id: step_two
             #                run: |
